name: CI

on:
  pull_request:
    branches: [master]

jobs:
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      ## NPM dir
      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      ## Cache
      - name: Cache npm cache
        uses: actions/cache@v2
        id: cache-npm-cache2
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm2-

      ## Cache
      - name: Cache node_modules
        id: cache-node-modules2
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules2-

      ## Cache
      - name: Cache Cypress
        id: cache-cypress2
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ matrix.node-version }}-cypress2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-cypress2-

      ## Dependencies
      - name: Install Dependencies
        if: |
          steps.cache-npm-cache.outputs.cache-hit != 'true' ||
          steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      ## Test
      - name: Start Vite devserver
        run: npm run start

      - name: Run tests
        run: npm run test:ci

      - name: Upload artifacts on fail
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: videos
          path: tests/e2e/videos/
